#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG); FILE_ROOT="$DOKKU_ROOT/$APP/DOKKU_TARBALLS"
verify_app_name "$APP"

if [[ -d "$FILE_ROOT" ]] && [[ -n $(ls -p "$FILE_ROOT") ]]; then
  dokku_log_info1 "Copying tar files into image..."
  for path in $FILE_ROOT/*.tar; do
    file=$(basename $path)
    dokku_log_verbose "- Copying Tar $file"
    id=$(docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/$file" < "$path")
    test "$(docker wait $id)" -eq 0
    docker commit $id $IMAGE > /dev/null
    docker stop $id > /dev/null 2>&1 || true
    docker kill $id > /dev/null 2>&1 || true
    
    dokku_log_verbose "- Extracting Tar $file"
    id2=$(docker run -d $IMAGE /bin/bash -c "tar -xf /app/$file -C /app")
    docker attach $id2
    test $(docker wait $id2) -eq 0
    docker commit $id2 $IMAGE > /dev/null
    docker stop $id2 > /dev/null 2>&1 || true
    docker kill $id2 > /dev/null 2>&1 || true
  done
fi
